steps:
  # Build the Docker image with BuildKit and caching enabled
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '--cache-from'
      - '${_IMAGE_NAME}:latest'
      - '--tag'
      - '${_IMAGE_NAME}:${SHORT_SHA}'
      - '--tag'
      - '${_IMAGE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMPOSE_DOCKER_CLI_BUILD=1'
    id: 'build'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_IMAGE_NAME}'
    id: 'push'

# Substitutions
substitutions:
  _IMAGE_NAME: 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/api-dev/api-go'

# Options for faster builds
options:
  machineType: 'E2_HIGHCPU_8'  # Use high-CPU machine for faster builds
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'
    - 'COMPOSE_DOCKER_CLI_BUILD=1'

# Timeout (optional, adjust as needed)
timeout: '1200s'  # 20 minutes

# Images to be pushed to the registry
images:
  - '${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_IMAGE_NAME}:latest'

