steps:
  # Pull the latest image to use as cache (fails gracefully if image doesn't exist)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull ${_IMAGE_NAME}:latest || exit 0'
    id: 'pull-cache'

  # Build the Docker image with layer caching enabled
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '--cache-from'
      - '${_IMAGE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
    id: 'build'
    waitFor: ['pull-cache']

# Substitutions
substitutions:
  _IMAGE_NAME: 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/api-dev/api-go'

# Options for faster builds
options:
  # Use high-CPU machine for faster builds (uncomment if you have permission)
  # machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'

# Timeout (optional, adjust as needed)
timeout: '1200s'  # 20 minutes

# Images to be pushed to the registry
images:
  - '${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_IMAGE_NAME}:latest'

