steps:
  # Pull the latest image to use its inline cache (fails gracefully if image doesn't exist)
  # Inline cache is embedded in the image layers, so we pull the image itself
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull asia-northeast1-docker.pkg.dev/$PROJECT_ID/api-dev/api-go:latest || exit 0
    id: 'pull-cache'

  # Build the Docker image with BuildKit inline cache
  # Build context is repo root (.) to access both apps/api-go and apps/builder
  # Dockerfile path is relative to build context (repo root)
  # Inline cache is embedded in image layers, eliminating the need for separate cache images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/api-dev/api-go:${_TAG}'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/api-dev/api-go:latest'
      - '--cache-from'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/api-dev/api-go:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-f'
      - 'apps/api-go/Dockerfile'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
    id: 'build'
    waitFor: ['pull-cache']

# Options optimized for FREE TIER usage
options:
  # Machine type: E2_MEDIUM (qualifies for free tier)
  # 
  # FREE TIER: 2,500 build-minutes per month on E2_MEDIUM/e2-standard-2 machine type
  # - This allows ~500 builds/month (assuming 5min per build)
  # - With caching optimizations, subsequent builds are 1-3min, allowing ~800-2,500 builds/month
  # 
  # Cost analysis (if exceeding free tier):
  # - E2_MEDIUM: 5min × $0.003 = $0.015 per build (FREE within 2,500 min/month)
  # - E2_HIGHCPU_8: 2min × $0.0156 = $0.031 per build (NOT eligible for free tier, always paid)
  # 
  # To use E2_HIGHCPU_8 for faster builds (NOT free tier), override via --machine-type flag
  # Recommendation: 
  # - ALWAYS use E2_MEDIUM (default) to maximize free tier usage
  # - With caching optimizations, builds will be 1-3min, well within free tier limits
  machineType: 'E2_MEDIUM'  # FREE TIER eligible - 2,500 build-minutes/month free
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'
  # Disk size: 100GB for caching (doesn't affect free tier eligibility)
  diskSizeGb: 100

# Timeout (optional, adjust as needed)
timeout: '1200s'  # 20 minutes

# Substitutions
# _TAG should be provided from GitHub Actions (commit SHA)
# If not provided, it will default to 'latest' (but GitHub Actions always provides it)
substitutions:
  _TAG: 'latest'

# Images to be pushed to the registry
# Use BUILD_ID as fallback if SHORT_SHA is not available
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/api-dev/api-go:${_TAG}'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/api-dev/api-go:latest'

